ip_forward: true
network_compression_threshold: 256
stats: ab656a18-017b-45a4-a200-851d0e2f511e
permissions:
  default: null
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.send
groups:
  Maxime3399:
  - admin
servers:
  Srv1:
    motd: ''
    address: localhost:30000
    restricted: false
  Srv2:
    motd: ''
    address: localhost:30001
    restricted: false
timeout: 30000
listeners:
- query_port: 25577
  motd: ''
  tab_list: SERVER
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    test.maxime3399.fr: Srv1
  ping_passthrough: false
  priorities:
  - Srv1
  - Srv2
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: false
prevent_proxy_connections: false
player_limit: -1
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
